server {
    listen 80;
    root /var/www/html;
    index index.html index.php;
    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    location /music/ {
        alias /var/www/html/music/;
    }
}
